[package]
name = "MidiSequencer"
version = "0.1.0"
edition = "2021"

[dependencies]
midir = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossterm = "0.29.0"
ratatui = "0.29.0"